name: saltstack-httpd-formula
source: https://github.com/bechtoldt/saltstack-httpd-formula
summary: SaltStack Formula to set up and configure httpd, the Apache HTTP Server
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
  - support load balancing
  - manage htpasswd files
  - chattr php.ini/ fcgi starter script?
